// src/pages/Employment.jsx
export default function Employment() {
  return (
    <div className="mt-12 spaced-y-10">
      <div>
        <a href="https://www.haader.com/" className="text-lg text-black font-bold no-underline hover:underline" target="_blank" rel="noreferrer">Software Engineer at Haader <small>[September 2022 - Present]</small></a><br />
        Haader is a Food, groceries & more, delivered quickly to your doorstep. Contactless delivery available. Fast and easy food & grocery delivery from the best restaurants and supermarkets near you. Order & Track Your Food. Fast & Easy Delivery. Simple Food Ordering
        <div className="text-grey-darkest text-base leading-normal mt-1">
          <ul>
            <li>Design parts in the application</li>
            <li>Building Restfull APIs for mobile and multiple dashboards</li>
            <li>Managed and maintained Servers</li>
          </ul>
        </div>
      </div>
      <div>
        <a href="https://www.bluecrunch.com/" className="text-lg text-black font-bold no-underline hover:underline" target="_blank" rel="noreferrer">Software Engineer at BlueCrunch <small>[November 2018 - August 2022]</small></a>
        <div className="text-grey-darkest text-base leading-normal mt-1">
          <ul>
            <li>
              <div className="text-grey-darkest text-base leading-normal mt-2"><a href="https://botter.ai" target="_blank" rel="noreferrer" className="text-grey-darker hover:text-black text-sm no-underline hover:underline">BOTTER</a></div>
              BOTTER.ai is a customer experience automation platform, it helps business deliver an enterprise conversational AI chatbots & VoiceBot with the power of integrated cognitive services and NLP
              <ul>
                <li>Built Restful API’s for flow builder dashboard</li>
                <li>Built Restful API’s used in the chatbot flow that integrate with the clients SAP applications.</li>
                <li>Built an escalation service that contains multiple integrations between the chatbot and the contact center management systems like genesys (cloud, pureconnect) or cisco (ECE, UCCX, UCCE)</li>
                <li>Built the chatbot core engine for botter v1</li>
                <li>Deploying and maintaing the product on primis in clients environment, (MOI, Housing Bank, Bank aljazira, Bupa, Mednet, Mansour, Hamat, MODON)</li>
              </ul>
            </li>
            <li>Built Restful API’s using Microservices architecture for autostore websites like Mansour, Toyota and Autostore</li>
            <li>Built Restful API’s for the mobile application management and CMS like loreal, benfix , Souk Okaz, BARQ and ValU</li>
            <li>Integrated with payment gateways like Stripe, PayPal and Payfort</li>
            <li>Designed a lot of projects database and implemented RESTful API for mobile applications and web platforms</li>
          </ul>
        </div>
      </div>
      <div>
        <span className="text-lg text-black font-bold no-underline">Software Engineer at Quadrant ME <small>[March 2018 - October 2018]</small></span>
        <div className="text-grey-darkest text-base leading-normal mt-1">
          <ul>
            <li>Unit and Browser testing, using PHPUnit and Laravel Dusk.</li>
            <li>Building messenger chat bot for qarenhom.com.</li>
          </ul>
          <div className="text-grey-darkest text-base leading-normal mt-2"><a href="https://www.qarenhom.com" target="_blank" rel="noreferrer" className="text-grey-darker hover:text-black text-sm no-underline hover:underline">Qarenhom</a></div>
        </div>
      </div>
      <div>
        <a href="https://bassmat.com/" className="text-lg text-black font-bold no-underline hover:underline" target="_blank" rel="noreferrer">Backend Developer at Bassmat <small>[March 2017]</small></a>
        <div className="text-grey-darkest text-base leading-normal mt-1"><ul><li>Building APIs. That integrate with twitter services</li></ul></div>
      </div>
    </div>
  )
}

// src/views/Employment.vue
<template>
    <div class="mt-12 spaced-y-10">
        <div>
            <a href="https://www.haader.com/" class="text-lg text-black font-bold no-underline hover:underline">
                Software Engineer at Haader <small>[September 2022 - Present]</small>
            </a><br>
            Haader is a Food, groceries & more, delivered quickly to your doorstep. Contactless delivery available. 
            Fast and easy food & grocery delivery from the best restaurants and supermarkets near you. Order & Track Your Food.
            Fast & Easy Delivery. Simple Food Ordering
            <p class="text-grey-darkest text-base leading-normal mt-1">
                <ul>
                    <li>Design parts in the application</li><br>
                    <li>Building Restfull APIs for mobile and multiple dashboards</li><br>
                    <li>Managed and maintained Servers</li><br>
                </ul>
            </p>
        </div>
        <div>
            <a href="https://www.bluecrunch.com/" class="text-lg text-black font-bold no-underline hover:underline">
                Software Engineer at BlueCrunch <small>[November 2018 - August 2022]</small>
            </a>
            <p class="text-grey-darkest text-base leading-normal mt-1">
                <ul>
                    <li>
                        <div class="text-grey-darkest text-base leading-normal mt-2">
                            <a href="https://botter.ai" target="__blank" class="text-grey-darker hover:text-black text-sm no-underline hover:underline">BOTTER</a>
                        </div>
                        BOTTER.ai is a customer experience automation platform, it helps business deliver an enterprise conversational
                        AI chatbots & VoiceBot with the power of integrated cognitive services and NLP
                        <ul>
                            <li>Built Restful API’s for flow builder dashboard</li>
                            <li>Built Restful API’s used in the chatbot flow that integrate with the clients SAP applications.</li>
                            <li>
                                Built an escalation service that contains multiple integrations between the chatbot and the contact center management systems like genesys (cloud, pureconnect) or cisco (ECE, UCCX, UCCE)
                            </li>
                            <li>Built the chatbot core engine for botter v1</li>
                            <li>
                                Deploying and maintaing the product on primis in clients environment, (MOI, Housing Bank, Bank aljazira, Bupa, Mednet, Mansour, Hamat, MODON)
                            </li>

                        </ul>
                    </li>
                    <br>
                    <li>
                        Built Restful API’s using Microservices architecture for autostore websites like Mansour, Toyota and Autostore
                    </li>
                    <br>
                    <li>
                        Built Restful API’s for the mobile application management and CMS like loreal, benfix , Souk Okaz, BARQ and ValU
                    </li>
                    <br>
                    <li>
                        Integrated with payment gateways like Stripe, PayPal and Payfort
                    </li>
                    <br>
                    <li>
                        Designed a lot of projects database and implemented RESTful API for mobile applications and web platforms
                    </li>
                </ul>
            </p>
        </div>

        <div>
            <a href="https://www.quadrantme.com/" class="text-lg text-black font-bold no-underline hover:underline">
                Software Engineer at Quadrant ME <small>[March 2018 - October 2018]</small>
            </a>
            <p class="text-grey-darkest text-base leading-normal mt-1">
                <ul>
                    <li>Unit and Browser testing, using PHPUnit and Laravel Dusk.</li><br>
                    <li>Building messenger chat bot for qarenhom.com.</li>
                    <div class="text-grey-darkest text-base leading-normal mt-2">
                        <a href="https://www.qarenhom.com" target="__blank" class="text-grey-darker hover:text-black text-sm no-underline hover:underline">Qarenhom</a>
                    </div>
                </ul>
            </p>
        </div>

        <div>
            <a href="https://bassmat.com/" class="text-lg text-black font-bold no-underline hover:underline">
                Backend Developer at Bassmat <small>[March 2017]</small>
            </a>
            <p class="text-grey-darkest text-base leading-normal mt-1">
                <ul>
                    <li>Building APIs</li>
                </ul>
            </p>
        </div>
    </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: 'Employment',
  components: {}
}
</script>
