// src/pages/Skills.jsx
export default function Skills() {
  return (
    <div className="mt-12 spaced-y-10">
      <div>
        <p className="text-lg text-black font-bold">Technical Skills and work knowledge:</p>
        <div className="text-grey-darkest text-base leading-normal mt-1">
          <ul>
            <li>TypeScript, JavaScript (ES6+), PHP, Go</li>
            <li>Node.js, NestJS, Laravel, REST APIs</li>
            <li>PostgreSQL, MongoDB, Redis, Elasticsearch</li>
            <li>Vue.js, React, Tailwind CSS, Sass</li>
            <li>System design, microservices architecture, performance optimization</li>
            {/* <li>Unit testing, integration testing, end-to-end testing</li> */}
          </ul>
        </div>
      </div>
      <div>
        <p className="text-lg text-black font-bold">Tools:</p>
        <div className="text-grey-darkest text-base leading-normal mt-1">
          <ul>
            <li>GNU/Linux, Bash scripting, Git, GitHub/GitLab workflows</li>
            <li>Docker, Kubernetes basics, CI/CD (GitHub Actions, GitLab CI)</li>
            <li>Postman, Swagger/OpenAPI</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

// src/views/Skills.vue
<template>
    <div class="mt-12 spaced-y-10">
        <div>
            <p class="text-lg text-black font-bold">
                Technical Skills and work knowledge:
            </p>
            <p class="text-grey-darkest text-base leading-normal mt-1">
                <ul>
                    <li>PHP, MySql, JavaScript, Laravel, Vue.js</li>
                    <li>Node.js, Express.js, MongoDB, React.js</li>
                    <li>Go, PostgreSQL</li>
                    <li>Bootstrap, Bulma, Material Design, CSS, Sass</li>
                    <li>Unit testing, Browser Testing</li>
                </ul>
            </p>
        </div>
        <div>
            <p class="text-lg text-black font-bold">
                Tools:
            </p>
            <p class="text-grey-darkest text-base leading-normal mt-1">
                <ul>
                    <li>GNU/Linux (Current OS), Bash Shell Scripting, Version control system (Git)</li>
                    <li>Docker, CI/CD tools, Elasticsearch, RabbitMQ, gRPC</li>
                </ul>
            </p>
        </div>
    </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: 'Skills',
  components: {}
}
</script>
