// src/views/Playground.vue
<template>
    <div>
        <div>
        <p class="text-lg text-black font-bold no-underline">
            Digital Assistant
        </p>
        <p class="text-grey-darkest text-base leading-normal mt-1">
            Extreme Solution Backend Challenge, Simple Appointment web application between doctors and patients using nodejs, python and
            golang for the back-end. Patient can view all the available time slots of a doctor so he would be able to make
            an appointment.
            <ul>
                <li>
                    REST
                    <div class="text-grey-darkest text-base leading-normal mt-2">
                        [<a href="https://github.com/MuhammadOrabi/assessment-task" target="__blank" class="text-grey-darker hover:text-black text-sm no-underline hover:underline">Github Repo</a>]
                    </div>
                </li>
                <br>
                <li>
                    Messaging over Message Broker using RabbitMQ
                    <div class="text-grey-darkest text-base leading-normal mt-2">
                        [<a href="https://gitlab.com/digital-assistant/app" target="__blank" class="text-grey-darker hover:text-black text-sm no-underline hover:underline">Gitlab Repo</a>] 
                    </div>
                </li>
            </ul>
        </p>
    </div>

    <div>
        <p class="text-lg text-black font-bold no-underline">
            Chat Module
        </p>
        <p class="text-grey-darkest text-base leading-normal mt-1">
            Instabug Back End Challenge, Simple chat module for testing out ruby with elasticsearch and simple go command line to interact with the chat module powered by cobra.
            <ul>
                <li>
                    <div class="text-grey-darkest text-base leading-normal mt-2">
                        [<a href="https://github.com/MuhammadOrabi/ruby-elasticsearch-go" target="__blank" class="text-grey-darker hover:text-black text-sm no-underline hover:underline">Github Repo</a>]
                    </div>
                </li>
            </ul>
        </p>
    </div>
    </div>
</template>

<script>
// @ is an alias to /src

export default {
  name: "Playground",
  components: {},
};
</script>

// src/pages/Playground.jsx
export default function Playground() {
  return (
    <div>
      <div>
        <p className="text-lg text-black font-bold no-underline">Digital Assistant</p>
        <div className="text-grey-darkest text-base leading-normal mt-1">
          Extreme Solution Backend Challenge, Simple Appointment web application between doctors and patients using nodejs, python and golang for the back-end. Patient can view all the available time slots of a doctor so he would be able to make an appointment.
          <ul>
            <li>
              REST
              <div className="text-grey-darkest text-base leading-normal mt-2">[
                <a href="https://github.com/MuhammadOrabi/assessment-task" target="_blank" rel="noreferrer" className="text-grey-darker hover:text-black text-sm no-underline hover:underline">Github Repo</a>
              ]</div>
            </li>
            <li>
              Messaging over Message Broker using RabbitMQ
              <div className="text-grey-darkest text-base leading-normal mt-2">[
                <a href="https://gitlab.com/digital-assistant/app" target="_blank" rel="noreferrer" className="text-grey-darker hover:text-black text-sm no-underline hover:underline">Gitlab Repo</a>
              ]</div>
            </li>
          </ul>
        </div>
      </div>
      <div>
        <p className="text-lg text-black font-bold no-underline">Chat Module</p>
        <div className="text-grey-darkest text-base leading-normal mt-1">
          Instabug Back End Challenge, Simple chat module for testing out ruby with elasticsearch and simple go command line to interact with the chat module powered by cobra.
          <ul>
            <li>
              <div className="text-grey-darkest text-base leading-normal mt-2">[
                <a href="https://github.com/MuhammadOrabi/ruby-elasticsearch-go" target="_blank" rel="noreferrer" className="text-grey-darker hover:text-black text-sm no-underline hover:underline">Github Repo</a>
              ]</div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  )
}
